twig:
    file_name_pattern: '*.twig'
    paths:
        'templates/layout': 'layout'
        'templates/component': 'component'
        'templates/Page': 'Page'

when@test:
    twig:
        strict_variables: true
